### ISSUE TITLE
Nginx client_max_body_size too low

### ISSUE THREAD

**Issue by ga-devfront** [PrestaShop/prestashop-flashlight#66]
Hello,
I am currently working with flashlight on themes as well as modules. However, when I try to add a theme from the BO which runs under Docker I encounter a major problem. Indeed, the nginx client_max_body_size is defined at 8MB while it is possible to have themes that can go up to 40MB, It is therefore impossible for me to add my themes.
I think it would therefore be good to increase this limit or pass it as a parameter.

**Comment by jokesterfr** [comment]
Hi @ga-devfront just ran into a discussion on this topic: https://github.com/PrestaShop/prestashop-flashlight/issues/68

Is 40M a definitive size for your need?

Please see https://github.com/PrestaShop/prestashop-flashlight/pull/67
